### ISSUE TITLE
404 linking Red Hat Universal Base Image in deploy.adoc

### ISSUE THREAD

**Issue by j1cken** [RedHatWorkshops/quarkus-workshop#20]
The following link in [docs/deploy.adoc](https://github.com/RedHat-Middleware-Workshops/quarkus-workshop/blob/master/docs/deploy.adoc#deploy-to-openshift-1) results in 404:

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html/getting_started_with_containers/using_red_hat_base_container_images_standard_and_minimal

**Comment by jamesfalkner** [comment]
Fixed! Thanks for the report!
