### ISSUE TITLE
Installation on clean AWS cluster fails

### ISSUE THREAD

**Issue by RHodzelmans** [RedHatWorkshops/quarkus-workshop#21]
Installation fails. The errors are legion, see etherpad below:
http://etherpad-opentlc-shared.apps.shared.na.openshift.opentlc.com/p/exception

Environment details: 
Client Version: openshift-clients-4.2.0-201910041700
Server Version: 4.4.10
Kubernetes Version: v1.17.1+9d33dd3

Che reports:
`Catalog Source Removed
The catalog source for this operator has been removed. The catalog source must be added back in order for this opertor to receive any updates.`

**Comment by danieloh30** [comment]
Try to run the bash script in OCP 4.4.8 cluster which you order in RHPDS(OpenShift 4.4 cluster) b/c user credentials are already created. Also, you need to install prerequisites to use this bash script: https://github.com/RedHat-Middleware-Workshops/quarkus-workshop#prerequisites

https://github.com/RedHat-Middleware-Workshops/quarkus-workshop/blob/master/setup/preparelab.sh
