### ISSUE TITLE
Using a devfile rather than importing a stack?

### ISSUE THREAD

**Issue by sunix** [RedHatWorkshops/quarkus-workshop#24]
Hello,
I have been through this workshop setup. I was wondering why not using a devfile.yaml to generate the workspace rather than importing the stack and asking the user to import the project.
WDYT?
I can help if needed

**Comment by sunix** [comment]
Not sure I have the right setup in master branch :/

**Comment by jamesfalkner** [comment]
The `preparelab.sh` script was written before we moved over to use AgnosticD to deploy. The [latest version](https://github.com/redhat-cop/agnosticd/tree/development/ansible/roles/ocp4-workload-quarkus-workshop) (using AgnosticD) does use a [devfile](https://github.com/redhat-cop/agnosticd/blob/development/ansible/roles/ocp4-workload-quarkus-workshop/templates/devfile.json.j2).

**Comment by sunix** [comment]
Thanks, will have a look. Good job BTW :+1: the workshop looks great!
