### ISSUE TITLE
Panache Lab: /person/birth/before/2000 will not return any results after late 2020

### ISSUE THREAD

**Issue by makuhama** [RedHatWorkshops/quarkus-workshop#25]
The fake persons inserted into the database have birthdays in the range [ now - 20 * 52weeks, now] - that's a little bit less than 20 years. So accessing the REST endpoint with

```
curl -s $(oc get route people -o=go-template --template={% raw %}'{{ .spec.host }}'{% endraw %})/person/birth/before/2000 | jq
```

will not produce any results by late 2020 (as then birthdays will only be in the year range [2001, 2020]). A quick fix will be to change the `2000` into `2001`. But then the same issue arises again one year later.

The documentation about the [workshopper](/RedHat-Middleware-Workshops/workshopper) itself is so terse that I'm unable to come up with a proper solution. No PR, sorry.

**Comment by jamesfalkner** [comment]
The first 3 hard-coded entries in `import.sql` do have birthdays before 2000 so you should at least get 3. But I'll fix the code so you get more, thanks for the y2k-esque heads-up!
